version: '2.4'
services:
  api:
    build:
      context: ./chat_api
    depends_on:
      db:
        condition: service_healthy
      message_broker:
        condition: service_healthy
    links: 
      - message_broker
    ports:
      - 8000:8000
    restart: always
  bot:
    build:
      context: ./chat_bot
    depends_on:
      message_broker:
        condition: service_healthy
    links: 
      - message_broker
    restart: always
  front:
    build:
      context: ./chat_frontend
    depends_on:
      - api
    ports:
      - 80:80
  db:
    image: 'postgres:12.4'
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d chat_db -U dev']
      interval: 50s
      timeout: 30s
      retries: 3
    volumes:
      - chat-db-volume:/var/lib/postgresql/data
  message_broker:
    image: rabbitmq:3-management
    hostname: rabbit-mq
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
    volumes:
      - rabbit-volume:/var/lib/rabbitmq
volumes:
  chat-db-volume:
  rabbit-volume:
